scalable/kwrite.svg: source/text-editor.svg
scalable/notepadqq.svg: source/text-editor.svg
scalable/application-vnd.efi.svg: source/haikuos-misc_uefi.svg
scalable/application-x-qemu-disk.svg: source/application-x-raw-disk-image.svg
scalable/application-x-iso9660-image.svg: source/application-x-cd-image.svg
scalable/application-x-compressed-iso.svg: source/application-x-cd-image.svg
scalable/application-x-dreamcast.rom.svg: source/zumi.xoom.it-system-iso.svg
scalable/application-x-gamecube.rom.svg: source/zumi.xoom.it-system-iso.svg
scalable/application-x-saturn.rom.svg: source/zumi.xoom.it-system-iso.svg
scalable/application-x-sega-cd.rom.svg: source/zumi.xoom.it-system-iso.svg
scalable/application-x-sega-pico.rom.svg: source/zumi.xoom.it-system-iso.svg
scalable/application-x-wii.rom.svg: source/zumi.xoom.it-system-iso.svg
scalable/application-vnd.recordare.musicxml+xml.svg: source/application-vnd.recordare.musicxml.svg
scalable/application-vnd.recordare.musicxml3.svg: source/application-vnd.recordare.musicxml.svg
scalable/application-vnd.recordare.musicxml3+xml.svg: source/application-vnd.recordare.musicxml.svg
scalable/application-vnd.abc.svg: source/text-vnd.abc.svg
scalable/gnome-character-map.svg: source/accessories-character-map.svg
scalable/gucharmap.svg: source/accessories-character-map.svg
scalable/kcharselect.svg: source/accessories-character-map.svg
scalable/accesorios.svg: source/accessories.svg
scalable/stock_new-address-book.svg: source/address-book-new.svg
scalable/gnome-panel-launcher.svg: source/app-launcher.svg
scalable/screenshot.svg: source/applets-screenshooter.svg
scalable/spectacle.svg: source/applets-screenshooter.svg
scalable/application-x-7z-compressed.svg: source/application-7zip.svg
scalable/stock_certificate.svg: source/application-certificate.svg
scalable/gnome-mime-application-msword.svg: source/application-msword.svg
scalable/gnome-pdf.svg: source/application-pdf.svg
scalable/gnome-mime-application-pdf.svg: source/application-pdf.svg
scalable/view_pdf.svg: source/application-pdf.svg
scalable/gnome-mime-application-postscript.svg: source/application-postscript.svg
scalable/gnome-mime-application-rtf.svg: source/application-rtf.svg
scalable/gnome-util.svg: source/applications-accessories.svg
scalable/package_utilities.svg: source/applications-accessories.svg
scalable/redhat-accessories.svg: source/applications-accessories.svg
scalable/xfce-utils.svg: source/applications-accessories.svg
scalable/gnome-devel.svg: source/applications-development.svg
scalable/package_development.svg: source/applications-development.svg
scalable/programacion.svg: source/applications-development.svg
scalable/programación.svg: source/applications-development.svg
scalable/redhat-programming.svg: source/applications-development.svg
scalable/xfce-devel.svg: source/applications-development.svg
scalable/educacion.svg: source/applications-education.svg
scalable/education.svg: source/applications-education.svg
scalable/juegos.svg: source/applications-games.svg
scalable/package_games.svg: source/applications-games.svg
scalable/redhat-games.svg: source/applications-games.svg
scalable/xfce-games.svg: source/applications-games.svg
scalable/avaible.svg: source/applications-internet.svg
scalable/gnome-globe.svg: source/applications-internet.svg
scalable/net.svg: source/applications-internet.svg
scalable/package_network.svg: source/applications-internet.svg
scalable/redhat-internet.svg: source/applications-internet.svg
scalable/stock_internet.svg: source/applications-internet.svg
scalable/xfce-internet.svg: source/applications-internet.svg
scalable/gnome-multimedia.svg: source/applications-multimedia.svg
scalable/multimedia.svg: source/applications-multimedia.svg
scalable/package_multimedia.svg: source/applications-multimedia.svg
scalable/redhat-sound_video.svg: source/applications-multimedia.svg
scalable/xfce-multimedia.svg: source/applications-multimedia.svg
scalable/gnome-applications.svg: source/applications-office.svg
scalable/loffice.svg: source/applications-office.svg
scalable/office.svg: source/applications-office.svg
scalable/oficina.svg: source/applications-office.svg
scalable/package_office.svg: source/applications-office.svg
scalable/redhat-office.svg: source/applications-office.svg
scalable/xfce-office.svg: source/applications-office.svg
scalable/gnome-other.svg: source/applications-other.svg
scalable/gnome-mime-application-vnd.ms-excel.svg: source/application-vnd.ms-excel.svg
scalable/application-vnd.oasis.opendocument.graphics.svg: source/application-vnd.oasis.opendocument.image.svg
scalable/application-vnd.sun.xml.draw.svg: source/application-vnd.oasis.opendocument.image.svg
scalable/application-vnd.sun.xml.calc.svg: source/application-vnd.oasis.opendocument.spreadsheet.svg
scalable/gnome-mime-application-vnd.sun.xml.calc.svg: source/application-vnd.oasis.opendocument.spreadsheet.svg
scalable/ooo_calc.svg: source/application-vnd.oasis.opendocument.spreadsheet.svg
scalable/application-vnd.stardivision.writer.svg: source/application-vnd.oasis.opendocument.text.svg
scalable/application-vnd.sun.xml.writer.svg: source/application-vnd.oasis.opendocument.text.svg
scalable/gnome-mime-application-vnd.sun.xml.writer.svg: source/application-vnd.oasis.opendocument.text.svg
scalable/libreoffice-oasis-text.svg: source/application-vnd.oasis.opendocument.text.svg
scalable/gnome-mime-application-x-bzip-compressed-tar.svg: source/application-x-bzip-compressed-tar.svg
scalable/gnome-mime-application-x-bzip.svg: source/application-x-bzip.svg
scalable/gnome-mime-application-x-compress.svg: source/application-x-compress.svg
scalable/application-x-core-file.svg: source/application-x-core.svg
scalable/gnome-mime-application-x-deb.svg: source/application-x-deb.svg
scalable/desktop-file.svg: source/application-x-desktop.svg
scalable/binary.svg: source/application-x-executable.svg
scalable/exec.svg: source/application-x-executable.svg
scalable/fs-executable.svg: source/application-x-executable.svg
scalable/mime-application-x-executable.svg: source/application-x-executable.svg
scalable/application-x-fictionbook+xml.svg: source/application-x-fictionbook.svg
scalable/video-x-flv.svg: source/application-x-flash-video.svg
scalable/application-x-font-afm.svg: source/application-x-font.svg
scalable/application-x-font-linux-psf.svg: source/application-x-font.svg
scalable/application-x-font-pcf.svg: source/application-x-font.svg
scalable/application-x-font-psf.svg: source/application-x-font.svg
scalable/application-x-font-speedo.svg: source/application-x-font.svg
scalable/application-gzip.svg: source/application-x-gzip.svg
scalable/gnome-mime-application-x-gzip.svg: source/application-x-gzip.svg
scalable/application-xml.svg: source/application-xhtml+xml.svg
scalable/text-xml.svg: source/application-xhtml+xml.svg
scalable/application-x-objectfile.svg: source/application-x-object.svg
scalable/gnome-mime-application-x-rar.svg: source/application-x-rar.svg
scalable/gnome-mime-application-x-rpm.svg: source/application-x-rpm.svg
scalable/gnome-mime-x-application-rpm.svg: source/application-x-rpm.svg
scalable/application-x-shared-library.svg: source/application-x-sharedlib.svg
scalable/tar.svg: source/application-x-tar.svg
scalable/gnome-mime-application-x-tar.svg: source/application-x-tar.svg
scalable/folder_tar.svg: source/application-x-tar.svg
scalable/tgz.svg: source/application-x-tgz.svg
scalable/application-x-compressed-tar.svg: source/application-x-tgz.svg
scalable/gnome-mime-application-x-compressed-tar.svg: source/application-x-tgz.svg
scalable/zip.svg: source/application-zip.svg
scalable/application-x-zip.svg: source/application-zip.svg
scalable/gnome-mime-application-zip.svg: source/application-zip.svg
scalable/stock_appointment-reminder-excl.svg: source/appointment-missed.svg
scalable/appointment-missed-symbolic.svg: source/appointment-missed.svg
scalable/appointment.svg: source/appointment-new.svg
scalable/stock_new-appointment.svg: source/appointment-new.svg
scalable/appointment-new-symbolic.svg: source/appointment-new.svg
scalable/stock_appointment-reminder.svg: source/appointment-soon.svg
scalable/appointment-soon-symbolic.svg: source/appointment-soon.svg
scalable/arrow-down.svg: source/arrow-down-green.svg
scalable/navigation_down.svg: source/arrow-down-green.svg
scalable/go-down.svg: source/arrow-down-green.svg
scalable/down.svg: source/arrow-down-green.svg
scalable/gtk-go-down.svg: source/arrow-down-green.svg
scalable/stock_down.svg: source/arrow-down-green.svg
scalable/go-bottom.svg: source/arrow-down-red.svg
scalable/bottom.svg: source/arrow-down-red.svg
scalable/gtk-goto-bottom.svg: source/arrow-down-red.svg
scalable/stock_bottom.svg: source/arrow-down-red.svg
scalable/go-first.svg: source/arrow-left-red.svg
scalable/gtk-goto-first-ltr.svg: source/arrow-left-red.svg
scalable/gtk-goto-last-rtl.svg: source/arrow-left-red.svg
scalable/start.svg: source/arrow-left-red.svg
scalable/stock_first.svg: source/arrow-left-red.svg
scalable/go-last.svg: source/arrow-right-red.svg
scalable/finish.svg: source/arrow-right-red.svg
scalable/gtk-goto-first-rtl.svg: source/arrow-right-red.svg
scalable/gtk-goto-last-ltr.svg: source/arrow-right-red.svg
scalable/stock_last.svg: source/arrow-right-red.svg
scalable/arrow-up.svg: source/arrow-up-green.svg
scalable/navigation_up.svg: source/arrow-up-green.svg
scalable/go-up.svg: source/arrow-up-green.svg
scalable/gtk-go-up.svg: source/arrow-up-green.svg
scalable/stock_up.svg: source/arrow-up-green.svg
scalable/up.svg: source/arrow-up-green.svg
scalable/go-top.svg: source/arrow-up-red.svg
scalable/gtk-goto-top.svg: source/arrow-up-red.svg
scalable/stock_top.svg: source/arrow-up-red.svg
scalable/top.svg: source/arrow-up-red.svg
scalable/yast_soundcard.svg: source/audio-card.svg
scalable/sound.svg: source/audio.svg
scalable/gnome-audio.svg: source/audio.svg
scalable/gnome-mime-audio.svg: source/audio.svg
scalable/emblem-sound.svg: source/audio.svg
scalable/audio-x-midi.svg: source/audio-midi.svg
scalable/gnome-mime-audio-x-midi.svg: source/audio-midi.svg
scalable/audio-volume-high-symbolic.svg: source/audio-volume-high.svg
scalable/stock_volume-max.svg: source/audio-volume-high.svg
scalable/stock_volume.svg: source/audio-volume-high.svg
scalable/xfce4-mixer-volume-high.svg: source/audio-volume-high.svg
scalable/xfce4-mixer-volume-very-high.svg: source/audio-volume-high.svg
scalable/stock-volume.svg: source/audio-volume-high.svg
scalable/player-volume.svg: source/audio-volume-high.svg
scalable/audio-volume-low-symbolic.svg: source/audio-volume-low.svg
scalable/stock_volume-0.svg: source/audio-volume-low.svg
scalable/stock_volume-min.svg: source/audio-volume-low.svg
scalable/xfce4-mixer-volume-low.svg: source/audio-volume-low.svg
scalable/xfce4-mixer-volume-ultra-low.svg: source/audio-volume-low.svg
scalable/audio-volume-medium-symbolic.svg: source/audio-volume-medium.svg
scalable/stock_volume-med.svg: source/audio-volume-medium.svg
scalable/xfce4-mixer-volume-low-medium.svg: source/audio-volume-medium.svg
scalable/xfce4-mixer-volume-medium.svg: source/audio-volume-medium.svg
scalable/audio-volume-muted-symbolic.svg: source/audio-volume-muted.svg
scalable/stock_volume-mute.svg: source/audio-volume-muted.svg
scalable/xfce4-mixer-muted.svg: source/audio-volume-muted.svg
scalable/xfce4-mixer-volume-muted.svg: source/audio-volume-muted.svg
scalable/audio-off.svg: source/audio-volume-muted.svg
scalable/gnome-mime-audio-x-aiff.svg: source/audio-x-aiff.svg
scalable/audio-flac.svg: source/audio-x-flac.svg
scalable/audio-basic.svg: source/haikuos-file_audio.svg
scalable/audio-x-generic.svg: source/haikuos-file_audio.svg
scalable/audio-generic.svg: source/haikuos-file_audio.svg
scalable/gnome-mime-audio-x-mp3.svg: source/audio-x-mp3.svg
scalable/audio-mpeg.svg: source/audio-x-mp3.svg
scalable/application-vnd.apple.mpegurl.svg: source/audio-x-mpegurl.svg
scalable/application-ogg.svg: source/audio-x-vorbis+ogg.svg
scalable/gnome-mime-application-ogg.svg: source/audio-x-vorbis+ogg.svg
scalable/gnome-mime-audio-x-wav.svg: source/audio-x-wav.svg
scalable/document-send.svg: source/avion_de_papel.svg
scalable/send.svg: source/avion_de_papel.svg
scalable/xfpm-primary-000-charging.svg: source/battery-000-charging.svg
scalable/battery-empty-charging-symbolic.svg: source/battery-000-charging.svg
scalable/xfpm-primary-000.svg: source/battery-000.svg
scalable/battery-empty-symbolic.svg: source/battery-000.svg
scalable/xfpm-primary-020-charging.svg: source/battery-020-charging.svg
scalable/battery-caution-charging-symbolic.svg: source/battery-020-charging.svg
scalable/xfpm-primary-020.svg: source/battery-020.svg
scalable/xfpm-primary-040-charging.svg: source/battery-040-charging.svg
scalable/xfpm-primary-040.svg: source/battery-040.svg
scalable/battery-good-charging-symbolic.svg: source/battery-060-charging.svg
scalable/xfpm-primary-060-charging.svg: source/battery-060-charging.svg
scalable/battery-good-symbolic.svg: source/battery-060.svg
scalable/xfpm-primary-060.svg: source/battery-060.svg
scalable/xfpm-primary-080-charging.svg: source/battery-080-charging.svg
scalable/xfpm-primary-080.svg: source/battery-080.svg
scalable/xfpm-primary-100-charging.svg: source/battery-100-charging.svg
scalable/battery-full-charging-symbolic.svg: source/battery-100-charging.svg
scalable/xfpm-primary-100.svg: source/battery-100.svg
scalable/xfpm-primary-caution.svg: source/battery-caution.svg
scalable/battery-caution-symbolic.svg: source/battery-caution.svg
scalable/xfpm-primary-charged.svg: source/battery-charged.svg
scalable/battery-full-charged-symbolic.svg: source/battery-charged.svg
scalable/battery-full-symbolic.svg: source/battery-full.svg
scalable/xfpm-primary-full.svg: source/battery-full.svg
scalable/gnome-dev-battery.svg: source/battery.svg
scalable/battery-low-charging-symbolic.svg: source/battery-low-charging.svg
scalable/xfpm-primary-low.svg: source/battery-low.svg
scalable/battery-low-symbolic.svg: source/battery-low.svg
scalable/xfpm-primary-missing.svg: source/battery-missing.svg
scalable/battery-missing-symbolic.svg: source/battery-missing.svg
scalable/bookmark_add.svg: source/bookmark-new.svg
scalable/bookmarks_list_add.svg: source/bookmark-new.svg
scalable/stock_add-bookmark.svg: source/bookmark-new.svg
scalable/stock_help-add-bookmark.svg: source/bookmark-new.svg
scalable/gnome-fs-bookmark.svg: source/bookmarks.svg
scalable/user-bookmarks.svg: source/bookmarks.svg
scalable/blackbox.svg: source/box-black.svg
scalable/emblem-bin.svg: source/box-black.svg
scalable/classviewer-var.svg: source/box-grey.svg
scalable/openbox.svg: source/box-grey.svg
scalable/emblem-box.svg: source/box-yellow.svg
scalable/date.svg: source/calendar.svg
scalable/ximian-evolution-calendar.svg: source/calendar.svg
scalable/x-office-calendar.svg: source/calendar.svg
scalable/plan.svg: source/calendar.svg
scalable/stock_calendar.svg: source/calendar.svg
scalable/vcalendar.svg: source/calendar.svg
scalable/evolution-calendar.svg: source/calendar.svg
scalable/gnome-calendar.svg: source/calendar.svg
scalable/office-calendar.svg: source/calendar.svg
scalable/office-date.svg: source/calendar.svg
scalable/xfcalendar.svg: source/calendar.svg
scalable/emblem-camera.svg: source/camera-photo.svg
scalable/camera.svg: source/camera-video.svg
scalable/video_player.svg: source/camera-video.svg
scalable/mplayer.svg: source/camera-video.svg
scalable/mpv.svg: source/camera-video.svg
scalable/camera-unmount.svg: source/camera-video-unmount.svg
scalable/camera_unmount.svg: source/camera-video-unmount.svg
scalable/codycam.svg: source/camera-web.svg
scalable/gnome-dev-camera.svg: source/camera-web.svg
scalable/skype.svg: source/camera-web.svg
scalable/vanity.svg: source/camera-web.svg
scalable/checkbox.svg: source/check.svg
scalable/checkbox-symbolic.svg: source/check.svg
scalable/gtk-apply.svg: source/checkmark.svg
scalable/gtk-ok.svg: source/checkmark.svg
scalable/ok.svg: source/checkmark.svg
scalable/checkbox-mixed.svg: source/check-mixed.svg
scalable/checkbox-mixed-symbolic.svg: source/check-mixed.svg
scalable/checkbox-checked.svg: source/check-pressed.svg
scalable/checkbox-checked-symbolic.svg: source/check-pressed.svg
scalable/gnome-glchess.svg: source/chess.svg
scalable/pychess.svg: source/chess.svg
scalable/alarm-symbolic.svg: source/clock.svg
scalable/emblem-urgent.svg: source/clock.svg
scalable/media-track-length.svg: source/clock.svg
scalable/classviewer-class.svg: source/code-class.svg
scalable/classviewer-namespace.svg: source/code-context.svg
scalable/dialog-fill-and-stroke.svg: source/colorchooser.svg
scalable/gmpc-no-cover.svg: source/compact_disc.svg
scalable/computer-fail-symbolic.svg: source/computer-fail.svg
scalable/gnome-dev-computer.svg: source/computer.svg
scalable/my-computer.svg: source/computer.svg
scalable/stock_new-bcard.svg: source/contact-new.svg
scalable/content-loading-symbolic.svg: source/content-loading.svg
scalable/image-loading.svg: source/content-loading.svg
scalable/gnome-fs-loading-icon.svg: source/content-loading.svg
scalable/gnome-cpu-frequency-applet.svg: source/cpu-frequency.svg
scalable/gnome-cpu.svg: source/cpu.svg
scalable/emblem-danger.svg: source/danger.svg
scalable/gnome-desktop-config.svg: source/desktop-config.svg
scalable/emblem-desktop.svg: source/desktop.svg
scalable/escritorio.svg: source/desktop.svg
scalable/perlpanel-applet-showdesktop.svg: source/desktop.svg
scalable/user-desktop.svg: source/desktop.svg
scalable/gnome-fs-desktop.svg: source/desktop.svg
scalable/gnome-ccdesktop.svg: source/desktop.svg
scalable/cd-autorun.svg: source/dev-autorun.svg
scalable/autorun.svg: source/dev-autorun.svg
scalable/dialog-ok.svg: source/dialog-apply.svg
scalable/dialog-yes.svg: source/dialog-apply.svg
scalable/rox-mounted.svg: source/dialog-apply.svg
scalable/dialog_information.svg: source/dialog-information.svg
scalable/dialog-information-symbolic.svg: source/dialog-information.svg
scalable/dialog_info.svg: source/dialog-information.svg
scalable/gtk-dialog-info.svg: source/dialog-information.svg
scalable/messagebox_info.svg: source/dialog-information.svg
scalable/stock_dialog-info.svg: source/dialog-information.svg
scalable/dialog-password-symbolic.svg: source/dialog-password.svg
scalable/gtk-dialog-authentication.svg: source/dialog-password.svg
scalable/stock_keyring.svg: source/dialog-password.svg
scalable/dialog_question.svg: source/dialog-question.svg
scalable/dialog-question-symbolic.svg: source/dialog-question.svg
scalable/gtk-dialog-question.svg: source/dialog-question.svg
scalable/stock_dialog-question.svg: source/dialog-question.svg
scalable/display-brightness-symbolic.svg: source/display-brightness.svg
scalable/xfpm-brightness-lcd.svg: source/display-brightness.svg
scalable/brightnesssettings.svg: source/display-brightness.svg
scalable/avant-window-navigator.svg: source/dock.svg
scalable/awn-manager.svg: source/dock.svg
scalable/filenew.svg: source/document-new.svg
scalable/gtk-new.svg: source/document-new.svg
scalable/new.svg: source/document-new.svg
scalable/stock_new-text.svg: source/document-new.svg
scalable/stock_print-setup.svg: source/document-page-setup.svg
scalable/fileprint.svg: source/document-print.svg
scalable/gtk-print.svg: source/document-print.svg
scalable/stock_print.svg: source/document-print.svg
scalable/filequickprint.svg: source/document-print-preview.svg
scalable/gtk-print-preview.svg: source/document-print-preview.svg
scalable/stock_print-preview.svg: source/document-print-preview.svg
scalable/print-preview.svg: source/document-print-preview.svg
scalable/properties.svg: source/document-properties.svg
scalable/stock_file-properites.svg: source/document-properties.svg
scalable/stock_properties.svg: source/document-properties.svg
scalable/gtk-revert-to-saved-ltr.svg: source/document-revert.svg
scalable/gtk-revert-to-saved-rtl.svg: source/document-revert.svg
scalable/revert.svg: source/document-revert.svg
scalable/emblem-downloads.svg: source/download-from-internet.svg
scalable/cajon.svg: source/drawer.svg
scalable/file-manager.svg: source/drawer.svg
scalable/kfm.svg: source/drawer.svg
scalable/redhat-filemanager.svg: source/drawer.svg
scalable/rox.svg: source/drawer.svg
scalable/system-file-manager.svg: source/drawer.svg
scalable/thunar.svg: source/drawer.svg
scalable/Thunar.svg: source/drawer.svg
scalable/xfce-filemanager.svg: source/drawer.svg
scalable/filebrowser.svg: source/drawer.svg
scalable/drive-cdrom.svg: source/drive-optical.svg
scalable/usbpendrive_unmount.svg: source/drive-removable-media.svg
scalable/xfce-mount.svg: source/drive-removable-media.svg
scalable/editclear.svg: source/edit-clear.svg
scalable/gtk-clear.svg: source/edit-clear.svg
scalable/clear.svg: source/edit-clear.svg
scalable/editdelete.svg: source/edit-delete.svg
scalable/gtk-delete.svg: source/edit-delete.svg
scalable/stock_delete.svg: source/edit-delete.svg
scalable/stock-gtk-remove.svg: source/edit-delete.svg
scalable/filefind.svg: source/edit-find.svg
scalable/gtk-find.svg: source/edit-find.svg
scalable/stock_search.svg: source/edit-find.svg
scalable/search.svg: source/edit-find.svg
scalable/find-and-replace.svg: source/edit-find-replace.svg
scalable/findreplace.svg: source/edit-find-replace.svg
scalable/gtk-find-and-replace.svg: source/edit-find-replace.svg
scalable/replace.svg: source/edit-find-replace.svg
scalable/stock_search-and-replace.svg: source/edit-find-replace.svg
scalable/editpaste.svg: source/edit-paste.svg
scalable/gtk-paste.svg: source/edit-paste.svg
scalable/parcellite.svg: source/edit-paste.svg
scalable/paste.svg: source/edit-paste.svg
scalable/stock_paste.svg: source/edit-paste.svg
scalable/gtk-redo-ltr.svg: source/edit-redo.svg
scalable/redo.svg: source/edit-redo.svg
scalable/stock_redo.svg: source/edit-redo.svg
scalable/gtk-select-all.svg: source/edit-select-all.svg
scalable/rox-select.svg: source/edit-select-all.svg
scalable/stock_select-all.svg: source/edit-select-all.svg
scalable/gtk-undo-ltr.svg: source/edit-undo.svg
scalable/stock_undo.svg: source/edit-undo.svg
scalable/undo.svg: source/edit-undo.svg
scalable/edit-copy.svg: source/emoji_u1f40f-black.svg
scalable/copy.svg: source/emoji_u1f40f-black.svg
scalable/editcopy.svg: source/emoji_u1f40f-black.svg
scalable/gtk-copy.svg: source/emoji_u1f40f-black.svg
scalable/stock_copy.svg: source/emoji_u1f40f-black.svg
scalable/gpicview.svg: source/eog.svg
scalable/ristretto.svg: source/eog.svg
scalable/logout.svg: source/exit.svg
scalable/application-exit.svg: source/exit.svg
scalable/salida.svg: source/exit.svg
scalable/gtk-quit.svg: source/exit.svg
scalable/xfce-system-exit.svg: source/exit.svg
scalable/stock_smiley-18.svg: source/face-angel.svg
scalable/stock_smiley-15.svg: source/face-cool.svg
scalable/stock_smiley-11.svg: source/face-crying.svg
scalable/stock_smiley-13.svg: source/face-kiss.svg
scalable/stock_smiley-22.svg: source/face-monkey.svg
scalable/stock_smiley-8.svg: source/face-plain.svg
scalable/stock_smiley-10.svg: source/face-raspberry.svg
scalable/stock_smiley-4.svg: source/face-sad.svg
scalable/gaim_insert-smiley-small.svg: source/face-smile-big.svg
scalable/stock_smiley-6.svg: source/face-smile-big.svg
scalable/stock_smiley-1.svg: source/face-smile.svg
scalable/stock_smiley-2.svg: source/face-smile.svg
scalable/stock_smiley-7.svg: source/face-smile.svg
scalable/stock_smiley-5.svg: source/face-surprise.svg
scalable/stock_smiley-3.svg: source/face-wink.svg
scalable/help-faq.svg: source/faq.svg
scalable/window-place_again.svg: source/faro.svg
scalable/ep-history.svg: source/file-clock.svg
scalable/file-generic.svg: source/file-white.svg
scalable/dnd.svg: source/file-white.svg
scalable/gtk-file.svg: source/file-white.svg
scalable/fs-regular.svg: source/file-white.svg
scalable/gnome-fs-regular.svg: source/file-white.svg
scalable/media-floppy.svg: source/floppy-2.svg
scalable/3floppy_unmount.svg: source/floppy-2.svg
scalable/gtk-floppy.svg: source/floppy-2.svg
scalable/system-floppy.svg: source/floppy-2.svg
scalable/gnome-dev-floppy.svg: source/floppy-3.svg
scalable/floppy.svg: source/floppy-black.svg
scalable/disk-floppy.svg: source/floppy-black.svg
scalable/document-save.svg: source/floppy-black.svg
scalable/filesave.svg: source/floppy-black.svg
scalable/gtk-save.svg: source/floppy-black.svg
scalable/stock_save.svg: source/floppy-black.svg
scalable/save.svg: source/floppy-black.svg
scalable/system-save-session.svg: source/floppy-black.svg
scalable/kfloppy.svg: source/floppy-black.svg
scalable/document-save-as.svg: source/floppy-blue.svg
scalable/gtk-save-as.svg: source/floppy-blue.svg
scalable/filesaveas.svg: source/floppy-blue.svg
scalable/stock_save-as.svg: source/floppy-blue.svg
scalable/save-as.svg: source/floppy-blue.svg
scalable/save_as.svg: source/floppy-blue.svg
scalable/guest.svg: source/fly.svg
scalable/gnome-fs-directory-accept.svg: source/folder-drag-accept.svg
scalable/folder-lock.svg: source/folder-locked.svg
scalable/folder_new.svg: source/folder-new.svg
scalable/stock_new-dir.svg: source/folder-new.svg
scalable/directory-open.svg: source/folder-open.svg
scalable/document_open.svg: source/folder-open.svg
scalable/document-open.svg: source/folder-open.svg
scalable/folder_open.svg: source/folder-open.svg
scalable/gtk-directory.svg: source/folder-open.svg
scalable/open.svg: source/folder-open.svg
scalable/stock_open.svg: source/folder-open.svg
scalable/fileopen.svg: source/folder-open.svg
scalable/gtk-open.svg: source/folder-open.svg
scalable/gnome-fs-share.svg: source/folder-remote.svg
scalable/gnome-mime-x-directory-smb-share.svg: source/folder-remote.svg
scalable/network.svg: source/folder-remote.svg
scalable/application-x-gnome-saved-search.svg: source/folder-saved-search.svg
scalable/gnome-fs-directory-visiting.svg: source/folder-visiting.svg
scalable/folder.svg: source/folder-yellow.svg
scalable/gnome-fs-directory.svg: source/folder-yellow.svg
scalable/inode-directory.svg: source/folder-yellow.svg
scalable/mime-inode-directory.svg: source/folder-yellow.svg
scalable/stock_folder.svg: source/folder-yellow.svg
scalable/font-capplet.svg: source/fonts-capplet.svg
scalable/fonts.svg: source/fonts-capplet.svg
scalable/gnome-settings-font.svg: source/font-settings.svg
scalable/application-x-font-bdf.svg: source/font-x-generic.svg
scalable/application-x-font-sunos-news.svg: source/font-x-generic.svg
scalable/font_bitmap.svg: source/font-x-generic.svg
scalable/font_truetype.svg: source/font-x-generic.svg
scalable/font_type1.svg: source/font-x-generic.svg
scalable/x-font-afm.svg: source/font-x-generic.svg
scalable/font_size_smaller.svg: source/format-font-size-less.svg
scalable/font_size_larger.svg: source/format-font-size-more.svg
scalable/gnome-stock-text-unindent.svg: source/format-indent-less.svg
scalable/gtk-indent-rtl.svg: source/format-indent-less.svg
scalable/gtk-unindent-ltr.svg: source/format-indent-less.svg
scalable/stock_text_unindent.svg: source/format-indent-less.svg
scalable/gnome-stock-text-indent.svg: source/format-indent-more.svg
scalable/gtk-indent-ltr.svg: source/format-indent-more.svg
scalable/gtk-unindent-rtl.svg: source/format-indent-more.svg
scalable/stock_text_indent.svg: source/format-indent-more.svg
scalable/centrejust.svg: source/format-justify-center.svg
scalable/gtk-justify-center.svg: source/format-justify-center.svg
scalable/stock_text_center.svg: source/format-justify-center.svg
scalable/gtk-justify-fill.svg: source/format-justify-fill.svg
scalable/stock_text_justify.svg: source/format-justify-fill.svg
scalable/gtk-justify-left.svg: source/format-justify-left.svg
scalable/leftjust.svg: source/format-justify-left.svg
scalable/stock_text_left.svg: source/format-justify-left.svg
scalable/gtk-justify-right.svg: source/format-justify-right.svg
scalable/rightjust.svg: source/format-justify-right.svg
scalable/stock_text_right.svg: source/format-justify-right.svg
scalable/gtk-bold.svg: source/format-text-bold.svg
scalable/stock_text_bold.svg: source/format-text-bold.svg
scalable/text_bold.svg: source/format-text-bold.svg
scalable/gtk-italic.svg: source/format-text-italic.svg
scalable/stock_text_italic.svg: source/format-text-italic.svg
scalable/text_italic.svg: source/format-text-italic.svg
scalable/gtk-strikethrough.svg: source/format-text-strikethrough.svg
scalable/stock_text-strikethrough.svg: source/format-text-strikethrough.svg
scalable/text_strike.svg: source/format-text-strikethrough.svg
scalable/gtk-underline.svg: source/format-text-underline.svg
scalable/stock_text_underlined.svg: source/format-text-underline.svg
scalable/text_under.svg: source/format-text-underline.svg
scalable/gimp-logo.svg: source/gimp.svg
scalable/wilber.svg: source/gimp.svg
scalable/sonata_disconnect.svg: source/gmpc-tray-disconnected.svg
scalable/sonata_pause.svg: source/gmpc-tray-pause.svg
scalable/pa.svg: source/gmpc-tray-play.svg
scalable/sonata_play.svg: source/gmpc-tray-play.svg
scalable/gnome-dev-harddisk-1394.svg: source/gnome-dev-firewire.svg
scalable/gnome-eyes-applet.svg: source/gnome-eyes.svg
scalable/awn-applet-digital-clock.svg: source/gnome-panel-clock.svg
scalable/microphone.svg: source/haiku-microphone.svg
scalable/audio-input-microphone.svg: source/haiku-microphone.svg
scalable/gnome-stock-mic.svg: source/haiku-microphone.svg
scalable/stock_mic.svg: source/haiku-microphone.svg
scalable/navigation_left.svg: source/haikuos-action_goback_1.svg
scalable/go-previous.svg: source/haikuos-action_goback_1.svg
scalable/back.svg: source/haikuos-action_goback_1.svg
scalable/gtk-go-back-ltr.svg: source/haikuos-action_goback_1.svg
scalable/gtk-go-forward-rtl.svg: source/haikuos-action_goback_1.svg
scalable/previous.svg: source/haikuos-action_goback_1.svg
scalable/stock_left.svg: source/haikuos-action_goback_1.svg
scalable/go-back.svg: source/haikuos-action_goback_1.svg
scalable/navigation_right.svg: source/haikuos-action_goforward_1.svg
scalable/go-next.svg: source/haikuos-action_goforward_1.svg
scalable/forward.svg: source/haikuos-action_goforward_1.svg
scalable/gtk-go-back-rtl.svg: source/haikuos-action_goforward_1.svg
scalable/gtk-go-forward-ltr.svg: source/haikuos-action_goforward_1.svg
scalable/next.svg: source/haikuos-action_goforward_1.svg
scalable/stock_right.svg: source/haikuos-action_goforward_1.svg
scalable/go-forward.svg: source/haikuos-action_goforward_1.svg
scalable/lock-open.svg: source/haikuos-action_login.svg
scalable/lock_open.svg: source/haikuos-action_login.svg
scalable/gdu-encrypted-unlock.svg: source/haikuos-action_login.svg
scalable/changes-allow.svg: source/haikuos-action_login.svg
scalable/changes-allow-symbolic.svg: source/haikuos-action_login.svg
scalable/object-unlocked.svg: source/haikuos-action_login.svg
scalable/lock-close.svg: source/haikuos-action_logout.svg
scalable/lock_close.svg: source/haikuos-action_logout.svg
scalable/gdu-encrypted-lock.svg: source/haikuos-action_logout.svg
scalable/password.svg: source/haikuos-action_logout.svg
scalable/changes-prevent.svg: source/haikuos-action_logout.svg
scalable/changes-prevent-symbolic.svg: source/haikuos-action_logout.svg
scalable/channel-secure.svg: source/haikuos-action_logout.svg
scalable/channel-secure-symbolic.svg: source/haikuos-action_logout.svg
scalable/object-locked.svg: source/haikuos-action_logout.svg
scalable/logviewer.svg: source/retrosmart-logviewer.svg
scalable/file-search.svg: source/haikuos-action_search.svg
scalable/process-stop.svg: source/haikuos-action_stop.svg
scalable/gtk-cancel.svg: source/haikuos-action_stop.svg
scalable/gtk-stop.svg: source/haikuos-action_stop.svg
scalable/stock_stop.svg: source/haikuos-action_stop.svg
scalable/stop.svg: source/haikuos-action_stop.svg
scalable/navigation_stop.svg: source/haikuos-action_stop.svg
scalable/close.svg: source/haikuos-action_stop.svg
scalable/emblem-idea.svg: source/haikuos-alert_idea.svg
scalable/information.svg: source/haikuos-alert_info.svg
scalable/info.svg: source/haikuos-alert_info.svg
scalable/window-identify.svg: source/haikuos-alert_info.svg
scalable/emblem-information.svg: source/haikuos-alert_info.svg
scalable/metadata.svg: source/haikuos-alert_info.svg
scalable/dialog-error.svg: source/haikuos-alert_stop.svg
scalable/dialog_error.svg: source/haikuos-alert_stop.svg
scalable/dialog-error-symbolic.svg: source/haikuos-alert_stop.svg
scalable/error.svg: source/haikuos-alert_stop.svg
scalable/gtk-dialog-error.svg: source/haikuos-alert_stop.svg
scalable/messagebox_critical.svg: source/haikuos-alert_stop.svg
scalable/stock_dialog-error.svg: source/haikuos-alert_stop.svg
scalable/emblem-warning.svg: source/haikuos-alert_warning.svg
scalable/emblem-important.svg: source/haikuos-alert_warning.svg
scalable/dialog-warning.svg: source/haikuos-alert_warning.svg
scalable/dialog_warning.svg: source/haikuos-alert_warning.svg
scalable/dialog-warning-symbolic.svg: source/haikuos-alert_warning.svg
scalable/gtk-dialog-warning.svg: source/haikuos-alert_warning.svg
scalable/important.svg: source/haikuos-alert_warning.svg
scalable/messagebox_warning.svg: source/haikuos-alert_warning.svg
scalable/stock_dialog-warning.svg: source/haikuos-alert_warning.svg
scalable/gnome-robots.svg: source/haikuos-app_automator.svg
scalable/docker.svg: source/haikuos-app_bikeshed.svg
scalable/systray.svg: source/haikuos-app_bikeshed.svg
scalable/calculadora.svg: source/haikuos-app_calculator_2.svg
scalable/accessories-calculator.svg: source/haikuos-app_calculator_2.svg
scalable/galculator.svg: source/haikuos-app_calculator_2.svg
scalable/calc.svg: source/haikuos-app_calculator_2.svg
scalable/calculator.svg: source/haikuos-app_calculator_2.svg
scalable/gcalctool.svg: source/haikuos-app_calculator_2.svg
scalable/gnome-calc3.svg: source/haikuos-app_calculator_2.svg
scalable/gnome-calculator.svg: source/haikuos-app_calculator_2.svg
scalable/kcalc.svg: source/haikuos-app_calculator_2.svg
scalable/brasero.svg: source/haikuos-app_cd_burner.svg
scalable/gnome-dev-cdwriter.svg: source/haikuos-app_cd_burner.svg
scalable/stock_xfburn-burn-cd.svg: source/haikuos-app_cd_burner.svg
scalable/tvm-burn-cd.svg: source/haikuos-app_cd_burner.svg
scalable/tools-media-optical-burn-image.svg: source/haikuos-app_cd_burner.svg
scalable/chat.svg: source/haikuos-app_chat.svg
scalable/internet-group-chat.svg: source/haikuos-app_chat.svg
scalable/xchat.svg: source/haikuos-app_chat.svg
scalable/debug.svg: source/haikuos-app_debugger.svg
scalable/emblem-debug.svg: source/haikuos-app_debugger.svg
scalable/baobab.svg: source/haikuos-app_diskusage.svg
scalable/filelight.svg: source/haikuos-app_diskusage.svg
scalable/tap-extract-to.svg: source/haikuos-app_expander_3.svg
scalable/archive-extract.svg: source/haikuos-app_expander.svg
scalable/extract-archive.svg: source/haikuos-app_expander.svg
scalable/tap-extract.svg: source/haikuos-app_expander.svg
scalable/homebank.svg: source/haikuos-app_finance.svg
scalable/gnucash.svg: source/haikuos-app_finance.svg
scalable/draw-cuboid.svg: source/haikuos-app_gldirectmode.svg
scalable/start-here.svg: source/haikuos-app_haiku3d.svg
scalable/distributor-logo.svg: source/haikuos-app_haiku3d.svg
scalable/gnome-main-menu.svg: source/haikuos-app_haiku3d.svg
scalable/novell-button.svg: source/haikuos-app_haiku3d.svg
scalable/applications-graphics.svg: source/haikuos-app_imageeditor.svg
scalable/emblem-art.svg: source/haikuos-app_imageeditor.svg
scalable/gnome-graphics.svg: source/haikuos-app_imageeditor.svg
scalable/graficos.svg: source/haikuos-app_imageeditor.svg
scalable/package_graphics.svg: source/haikuos-app_imageeditor.svg
scalable/palette.svg: source/haikuos-app_imageeditor.svg
scalable/redhat-graphics.svg: source/haikuos-app_imageeditor.svg
scalable/xfce-graphics.svg: source/haikuos-app_imageeditor.svg
scalable/gpaint.svg: source/haikuos-app_imageeditor.svg
scalable/kolourpaint.svg: source/haikuos-app_imageeditor.svg
scalable/mypaint.svg: source/haikuos-app_imageeditor.svg
scalable/dibujo.svg: source/haikuos-app_imageeditor.svg
scalable/graphics.svg: source/haikuos-app_imageeditor.svg
scalable/system-run.svg: source/haikuos-app_launchbox.svg
scalable/gnome-run.svg: source/haikuos-app_launchbox.svg
scalable/grun.svg: source/haikuos-app_launchbox.svg
scalable/gtk-execute.svg: source/haikuos-app_launchbox.svg
scalable/lupa.svg: source/haikuos-app_magnify.svg
scalable/find.svg: source/haikuos-app_magnify.svg
scalable/viewer.svg: source/haikuos-app_magnify.svg
scalable/view.svg: source/haikuos-app_magnify.svg
scalable/zoom.svg: source/haikuos-app_magnify.svg
scalable/mail.svg: source/haikuos-app_mail.svg
scalable/no-mail.svg: source/haikuos-app_mail_none.svg
scalable/xfce-nomail.svg: source/haikuos-app_mail_none.svg
scalable/milkytracker.svg: source/haikuos-app_midiplayer.svg
scalable/tracker.svg: source/haikuos-app_midiplayer.svg
scalable/netsurf.svg: source/haikuos-app_netsurf_original.svg
scalable/ocp.svg: source/haikuos-app_opencubicplayer.svg
scalable/sound-recorder.svg: source/haikuos-app_soundrecorder.svg
scalable/audacity.svg: source/haikuos-app_soundrecorder.svg
scalable/gnome-sound-recorder.svg: source/haikuos-app_soundrecorder.svg
scalable/emblem-generic.svg: source/haikuos-app_teapot.svg
scalable/teapot.svg: source/haikuos-app_teapot.svg
scalable/emblem-default.svg: source/haikuos-app_teapot.svg
scalable/rox-xattr.svg: source/haikuos-app_teapot.svg
scalable/transmission.svg: source/haikuos-app_transmission.svg
scalable/transmission-qt.svg: source/haikuos-app_transmission.svg
scalable/tv.svg: source/haikuos-app_tv.svg
scalable/me-tv.svg: source/haikuos-app_tv.svg
scalable/virtualbox.svg: source/haikuos-app_virtualbox.svg
scalable/media-optical.svg: source/haikuos-device_cd.svg
scalable/cdrom.svg: source/haikuos-device_cd.svg
scalable/gnome-dev-cdrom.svg: source/haikuos-device_cd.svg
scalable/cdrom_unmount.svg: source/haikuos-device_cd.svg
scalable/cdwriter_unmount.svg: source/haikuos-device_cd.svg
scalable/gnome-dev-disc-cdr.svg: source/haikuos-device_cd.svg
scalable/gnome-dev-disc-cdrw.svg: source/haikuos-device_cd.svg
scalable/gtk-cdrom.svg: source/haikuos-device_cd.svg
scalable/clipboard.svg: source/haikuos-device_clipboard.svg
scalable/clipit.svg: source/haikuos-device_clipboard.svg
scalable/xfce4-clipman-plugin.svg: source/haikuos-device_clipboard.svg
scalable/copyq.svg: source/haikuos-device_clipboard.svg
scalable/harddisk-label.svg: source/haikuos-device_harddisk_development.svg
scalable/gnome-fs-blockdev.svg: source/haikuos-device_harddisk_development.svg
scalable/gnome-fs-filesystem.svg: source/haikuos-device_harddisk_development.svg
scalable/inode-blockdevice.svg: source/haikuos-device_harddisk_development.svg
scalable/harddisk.svg: source/haikuos-device_harddisk.svg
scalable/drive-harddisk.svg: source/haikuos-device_harddisk.svg
scalable/gnome-dev-harddisk.svg: source/haikuos-device_harddisk.svg
scalable/gtk-harddisk.svg: source/haikuos-device_harddisk.svg
scalable/harddrive.svg: source/haikuos-device_harddisk.svg
scalable/hdd_unmount.svg: source/haikuos-device_harddisk.svg
scalable/yast_HD.svg: source/haikuos-device_harddisk.svg
scalable/yast_idetude.svg: source/haikuos-device_harddisk.svg
scalable/media-flash-memory-stick.svg: source/haikuos-device_memorystick.svg
scalable/media-flash.svg: source/haikuos-device_pendrive.svg
scalable/media-flash-sd-mmc.svg: source/haikuos-device_sd.svg
scalable/sd.svg: source/haikuos-device_sd.svg
scalable/gnome-dev-media-cf.svg: source/haikuos-device_sd.svg
scalable/gnome-dev-media-sdmmc.svg: source/haikuos-device_sd.svg
scalable/gnome-dev-media-sm.svg: source/haikuos-device_sd.svg
scalable/package-x-generic.svg: source/haikuos-file_archive.svg
scalable/application-x-archive.svg: source/haikuos-file_archive.svg
scalable/application-x-arj.svg: source/haikuos-file_archive.svg
scalable/application-x-cpio-compressed.svg: source/haikuos-file_archive.svg
scalable/application-x-cpio.svg: source/haikuos-file_archive.svg
scalable/application-x-lha.svg: source/haikuos-file_archive.svg
scalable/application-x-lhz.svg: source/haikuos-file_archive.svg
scalable/application-x-lzma-compressed-tar.svg: source/haikuos-file_archive.svg
scalable/application-x-lzma.svg: source/haikuos-file_archive.svg
scalable/application-x-stuffit.svg: source/haikuos-file_archive.svg
scalable/deb.svg: source/haikuos-file_archive.svg
scalable/gnome-mime-application-x-jar.svg: source/haikuos-file_archive.svg
scalable/gnome-mime-application-x-java-archive.svg: source/haikuos-file_archive.svg
scalable/rpm.svg: source/haikuos-file_archive.svg
scalable/package.svg: source/haikuos-file_archive.svg
scalable/emblem-package.svg: source/haikuos-file_archive.svg
scalable/celestia.svg: source/haikuos-file_chart.svg
scalable/image.svg: source/haikuos-file_image_1.svg
scalable/gnome-mime-image.svg: source/haikuos-file_image_1.svg
scalable/emblem-photos.svg: source/haikuos-file_image_1.svg
scalable/emblem-pictures.svg: source/haikuos-file_image_1.svg
scalable/image-x-generic.svg: source/haikuos-file_image_1.svg
scalable/emblem-images.svg: source/haikuos-file_image_1.svg
scalable/image-bmp.svg: source/haikuos-file_image_2.svg
scalable/gnome-mime-image-bmp.svg: source/haikuos-file_image_2.svg
scalable/inode-fifo.svg: source/haikuos-file_pipe.svg
scalable/gnome-fs-fifo.svg: source/haikuos-file_pipe.svg
scalable/application-xspf+xml.svg: source/retrosmart-file_playlist_xml.svg
scalable/audio-x-mpegurl.svg: source/retrosmart-file_playlist_text.svg
scalable/media-playlist.svg: source/haikuos-file_playlist.svg
scalable/view-media-playlist.svg: source/haikuos-file_playlist.svg
scalable/akregator.svg: source/haikuos-file_rss_feed.svg
scalable/format-text-code.svg: source/haikuos-file_sourcecode.svg
scalable/view-calendar-birthday.svg: source/haikuos-misc_birthday_cake.svg
scalable/bomb.svg: source/haikuos-misc_bomb.svg
scalable/bomba.svg: source/haikuos-misc_bomb.svg
scalable/emblem-bomb.svg: source/haikuos-misc_bomb.svg
scalable/gnome-gnomine.svg: source/haikuos-misc_bomb.svg
scalable/gnomine.svg: source/haikuos-misc_bomb.svg
scalable/inode-core.svg: source/haikuos-misc_bomb.svg
scalable/window-destroy.svg: source/haikuos-misc_bomb.svg
scalable/gnome-mines.svg: source/haikuos-misc_bomb.svg
scalable/bomber.svg: source/haikuos-misc_bomb.svg
scalable/edit-bomb.svg: source/haikuos-misc_bomb.svg
scalable/screen.svg: source/haikuos-misc_imac.svg
scalable/no_installed.svg: source/haikuos-misc_rip.svg
scalable/rip.svg: source/haikuos-misc_rip.svg
scalable/gnome-dev-harddisk-usb.svg: source/haikuos-misc_usb_black.svg
scalable/drive-removable-media-usb.svg: source/haikuos-misc_usb_black.svg
scalable/gnome-dev-removable-usb.svg: source/haikuos-misc_usb_black.svg
scalable/theme.svg: source/haikuos-prefs_appearance.svg
scalable/preferences-desktop-theme.svg: source/haikuos-prefs_appearance.svg
scalable/style.svg: source/haikuos-prefs_appearance.svg
scalable/gnome-ccthemes.svg: source/haikuos-prefs_appearance.svg
scalable/gnome-settings-themes.svg: source/haikuos-prefs_appearance.svg
scalable/preferences-desktop-wallpaper.svg: source/haikuos-prefs_backgrounds.svg
scalable/background-capplet.svg: source/haikuos-prefs_backgrounds.svg
scalable/background.svg: source/haikuos-prefs_backgrounds.svg
scalable/wallpaper.svg: source/haikuos-prefs_backgrounds.svg
scalable/xfce4-backdrop.svg: source/haikuos-prefs_backgrounds.svg
scalable/preferences-system-bluetooth.svg: source/haikuos-prefs_bluetooth.svg
scalable/bluetooth.svg: source/haikuos-prefs_bluetooth.svg
scalable/bluetooth-applet.svg: source/zumi.xoom.it-system-bluetooth.svg
scalable/convert.svg: source/haikuos-prefs_datatranslation.svg
scalable/giver.svg: source/haikuos-prefs_datatranslation.svg
scalable/gtk-convert.svg: source/haikuos-prefs_datatranslation.svg
scalable/font.svg: source/haikuos-prefs_fonts.svg
scalable/preferences-desktop-font.svg: source/haikuos-prefs_fonts.svg
scalable/dialog-text-and-font.svg: source/haikuos-prefs_fonts.svg
scalable/input-keyboard.svg: source/haikuos-prefs_keyboard.svg
scalable/gnome-dev-keyboard.svg: source/haikuos-prefs_keyboard.svg
scalable/keyboard.svg: source/haikuos-prefs_keyboard.svg
scalable/kxkb.svg: source/haikuos-prefs_keyboard.svg
scalable/xfce4-keyboard.svg: source/haikuos-prefs_keyboard.svg
scalable/keyboard-shortcut.svg: source/haikuos-prefs_keyboard.svg
scalable/preferences-desktop.svg: source/haikuos-prefs_media.svg
scalable/gnome-control-center.svg: source/haikuos-prefs_media.svg
scalable/gnome-settings.svg: source/haikuos-prefs_media.svg
scalable/kcontrol.svg: source/haikuos-prefs_media.svg
scalable/redhat-preferences.svg: source/haikuos-prefs_media.svg
scalable/xfce4-settings.svg: source/haikuos-prefs_media.svg
scalable/adjustlevels.svg: source/haikuos-prefs_media.svg
scalable/qasmixer.svg: source/haikuos-prefs_media.svg
scalable/alacarte.svg: source/haikuos-prefs_menu.svg
scalable/preferences-system-network.svg: source/haikuos-prefs_network.svg
scalable/network-idle.svg: source/haikuos-prefs_network.svg
scalable/connect_established.svg: source/haikuos-prefs_network.svg
scalable/gnome-netstatus-idle.svg: source/haikuos-prefs_network.svg
scalable/network-idle-symbolic.svg: source/haikuos-prefs_network.svg
scalable/knemo-network-idle.svg: source/haikuos-prefs_network.svg
scalable/preferences-desktop-screensaver.svg: source/haikuos-prefs_screensaver.svg
scalable/kscreensaver.svg: source/haikuos-prefs_screensaver.svg
scalable/screensaver.svg: source/haikuos-prefs_screensaver.svg
scalable/xscreensaver.svg: source/haikuos-prefs_screensaver.svg
scalable/inode-chardevice.svg: source/haikuos-prefs_virtualmemory.svg
scalable/chardevice.svg: source/haikuos-prefs_virtualmemory.svg
scalable/gnome-fs-chardev.svg: source/haikuos-prefs_virtualmemory.svg
scalable/kmail.svg: source/haikuos-server_maildaemon.svg
scalable/claws-mail.svg: source/haikuos-server_maildaemon.svg
scalable/xfce-newmail.svg: source/haikuos-server_maildaemon.svg
scalable/anjuta.svg: source/haikuos-server_syslog.svg
scalable/edit-move.svg: source/haikuos-tracker_move.svg
scalable/config.svg: source/hammer.svg
scalable/hwbrowser.svg: source/hardware-info.svg
scalable/hwinfo.svg: source/hardware-info.svg
scalable/abiword.svg: source/hbbi-abiword.svg
scalable/abiword_48.svg: source/hbbi-abiword.svg
scalable/audacious.svg: source/hbbi-aplayer.svg
scalable/document-viewer.svg: source/hbbi-bepdf.svg
scalable/evince.svg: source/hbbi-bepdf.svg
scalable/okular.svg: source/hbbi-bepdf.svg
scalable/acrobat.svg: source/hbbi-bepdf.svg
scalable/acroread.svg: source/hbbi-bepdf.svg
scalable/qpdfview.svg: source/hbbi-bepdf.svg
scalable/preferences-desktop-color.svg: source/hbbi-colors!.svg
scalable/qmmp.svg: source/hbbi-soundplay.svg
scalable/gnome-favorites.svg: source/heart.svg
scalable/donate.svg: source/heart.svg
scalable/emblem-favorite.svg: source/heart.svg
scalable/bookmark.svg: source/heart.svg
scalable/stock_about.svg: source/help-about.svg
scalable/go-home.svg: source/home.svg
scalable/gohome.svg: source/home.svg
scalable/gnome-home.svg: source/home.svg
scalable/gtk-home.svg: source/home.svg
scalable/kfm_home.svg: source/home.svg
scalable/redhat-home.svg: source/home.svg
scalable/stock_home.svg: source/home.svg
scalable/comunicacion.svg: source/im.svg
scalable/pidgin.svg: source/im.svg
scalable/mail-folder-inbox.svg: source/inbox.svg
scalable/help-browser.svg: source/info-browser.svg
scalable/khelpcenter.svg: source/info-browser.svg
scalable/susehelpcenter.svg: source/info-browser.svg
scalable/xfce-man.svg: source/info-browser.svg
scalable/gnome-joystick.svg: source/input-gaming.svg
scalable/joystick.svg: source/input-gaming.svg
scalable/gnome-dev-mouse-ball.svg: source/input-mouse.svg
scalable/gnome-dev-mouse-optical.svg: source/input-mouse.svg
scalable/gnome-dev-mouse.svg: source/input-mouse.svg
scalable/mouse-capplet.svg: source/input-mouse.svg
scalable/mouse.svg: source/input-mouse.svg
scalable/xfce4-mouse.svg: source/input-mouse.svg
scalable/yast_mouse.svg: source/input-mouse.svg
scalable/amusements.svg: source/joystick2.svg
scalable/keyboard-brightness-symbolic.svg: source/keyboard-brightness.svg
scalable/channel-insecure.svg: source/lock-open-alarm.svg
scalable/channel-insecure-symbolic.svg: source/lock-open-alarm.svg
scalable/start-here-lxqt.svg: source/lxqt.svg
scalable/mainmenu.svg: source/lxqt.svg
scalable/helix.svg: source/lxqt.svg
scalable/stock_attach.svg: source/mail-attachment.svg
scalable/mail-attachment-symbolic.svg: source/mail-attachment.svg
scalable/gnome-stock-mail-fwd.svg: source/mail-forward.svg
scalable/mail_forward.svg: source/mail-forward.svg
scalable/stock_mail-forward.svg: source/mail-forward.svg
scalable/mail_spam.svg: source/mail-mark-junk.svg
scalable/gnome-stock-mail-new.svg: source/mail-message-new.svg
scalable/mail_new.svg: source/mail-message-new.svg
scalable/stock_mail-compose.svg: source/mail-message-new.svg
scalable/mail-read-symbolic.svg: source/mail-read.svg
scalable/internet-mail.svg: source/mail-read.svg
scalable/mail_generic.svg: source/mail-read.svg
scalable/stock_mail-open.svg: source/mail-read.svg
scalable/email.svg: source/mail-read.svg
scalable/redhat-email.svg: source/mail-read.svg
scalable/xfce-mail.svg: source/mail-read.svg
scalable/mail-replied-symbolic.svg: source/mail-replied.svg
scalable/stock_mail-replied.svg: source/mail-replied.svg
scalable/mail_replyall.svg: source/mail-reply-all.svg
scalable/stock_mail-reply-to-all.svg: source/mail-reply-all.svg
scalable/gnome-stock-mail-rpl.svg: source/mail-reply-sender.svg
scalable/mail_reply.svg: source/mail-reply-sender.svg
scalable/stock_mail-reply.svg: source/mail-reply-sender.svg
scalable/gnome-stock-mail-snd.svg: source/mail-send.svg
scalable/mail_send.svg: source/mail-send.svg
scalable/stock_mail-send.svg: source/mail-send.svg
scalable/stock_mail-send-receive.svg: source/mail-send-receive.svg
scalable/stock_mail-unread.svg: source/mail-unread.svg
scalable/mail-unread-symbolic.svg: source/mail-unread.svg
scalable/eject.svg: source/media-eject.svg
scalable/player_eject.svg: source/media-eject.svg
scalable/stock-media-eject.svg: source/media-eject.svg
scalable/dvd_unmount.svg: source/media-optical-dvd.svg
scalable/gnome-dev-disc-dvdram.svg: source/media-optical-dvd.svg
scalable/gnome-dev-disc-dvdrom.svg: source/media-optical-dvd.svg
scalable/gnome-dev-disc-dvdr-plus.svg: source/media-optical-dvd.svg
scalable/gnome-dev-disc-dvdr.svg: source/media-optical-dvd.svg
scalable/gnome-dev-disc-dvdrw.svg: source/media-optical-dvd.svg
scalable/gtk-media-pause.svg: source/media-playback-pause.svg
scalable/player_pause.svg: source/media-playback-pause.svg
scalable/stock_media-pause.svg: source/media-playback-pause.svg
scalable/stock-media-pause.svg: source/media-playback-pause.svg
scalable/emblem-pause.svg: source/media-playback-pause.svg
scalable/gtk-media-play-ltr.svg: source/media-playback-start.svg
scalable/player_play.svg: source/media-playback-start.svg
scalable/stock_media-play.svg: source/media-playback-start.svg
scalable/stock-media-play.svg: source/media-playback-start.svg
scalable/gtk-media-stop.svg: source/media-playback-stop.svg
scalable/player_stop.svg: source/media-playback-stop.svg
scalable/stock_media-stop.svg: source/media-playback-stop.svg
scalable/stock-media-stop.svg: source/media-playback-stop.svg
scalable/stock_repeat.svg: source/media-playlist-repeat.svg
scalable/media-playlist-repeat-symbolic.svg: source/media-playlist-repeat.svg
scalable/media-playlist-repeat-rtl-symbolic.svg: source/media-playlist-repeat-rtl.svg
scalable/stock_shuffle.svg: source/media-playlist-shuffle.svg
scalable/media-playlist-shuffle-symbolic.svg: source/media-playlist-shuffle.svg
scalable/media-playlist-shuffle-rtl-symbolic.svg: source/media-playlist-shuffle-rtl.svg
scalable/gtk-media-record.svg: source/media-record.svg
scalable/player_record.svg: source/media-record.svg
scalable/stock_media-rec.svg: source/media-record.svg
scalable/gtk-media-forward-rtl.svg: source/media-seek-backward.svg
scalable/gtk-media-rewind-ltr.svg: source/media-seek-backward.svg
scalable/player_rew.svg: source/media-seek-backward.svg
scalable/stock-media-rewind.svg: source/media-seek-backward.svg
scalable/stock_media-rew.svg: source/media-seek-backward.svg
scalable/gtk-media-forward-ltr.svg: source/media-seek-forward.svg
scalable/gtk-media-rewind-rtl.svg: source/media-seek-forward.svg
scalable/player_fwd.svg: source/media-seek-forward.svg
scalable/stock-media-ffwd.svg: source/media-seek-forward.svg
scalable/stock_media-fwd.svg: source/media-seek-forward.svg
scalable/gtk-media-next-rtl.svg: source/media-skip-backward.svg
scalable/gtk-media-previous-ltr.svg: source/media-skip-backward.svg
scalable/player_start.svg: source/media-skip-backward.svg
scalable/stock_media-prev.svg: source/media-skip-backward.svg
scalable/stock-media-prev.svg: source/media-skip-backward.svg
scalable/gtk-media-next-ltr.svg: source/media-skip-forward.svg
scalable/gtk-media-previous-rtl.svg: source/media-skip-forward.svg
scalable/player_end.svg: source/media-skip-forward.svg
scalable/stock_media-next.svg: source/media-skip-forward.svg
scalable/stock-media-next.svg: source/media-skip-forward.svg
scalable/ximian-redhat-config-nfs.svg: source/menu-apps-right.svg
scalable/perlpanel-applets-actions.svg: source/menu-apps-right.svg
scalable/wmdrawer.svg: source/menu-apps-right.svg
scalable/xfce4-menueditor.svg: source/menu-editor.svg
scalable/kmenuedit.svg: source/menu-editor.svg
scalable/microphone-sensitivity-high-symbolic.svg: source/microphone-sensitivity-high.svg
scalable/microphone-sensitivity-low-symbolic.svg: source/microphone-sensitivity-low.svg
scalable/microphone-sensitivity-medium-symbolic.svg: source/microphone-sensitivity-medium.svg
scalable/microphone-sensitivity-muted-symbolic.svg: source/microphone-sensitivity-muted.svg
scalable/restar.svg: source/minus.svg
scalable/list_remove.svg: source/minus.svg
scalable/list-remove.svg: source/minus.svg
scalable/gtk-remove.svg: source/minus.svg
scalable/remove.svg: source/minus.svg
scalable/gnome-modem.svg: source/modem.svg
scalable/dolphin-emu.svg: source/3deyes-dolphin.svg
scalable/firefox.svg: source/mozilla.svg
scalable/iceweasel.svg: source/mozilla.svg
scalable/mozilla-mail-icon.svg: source/mozilla-mail.svg
scalable/arts.svg: source/multimedia-volume-control.svg
scalable/gnome-alsamixer.svg: source/multimedia-volume-control.svg
scalable/gnome-mixer.svg: source/multimedia-volume-control.svg
scalable/gnome-volume-control.svg: source/multimedia-volume-control.svg
scalable/kcmsound.svg: source/multimedia-volume-control.svg
scalable/pavucontrol.svg: source/multimedia-volume-control.svg
scalable/volume-knob.svg: source/multimedia-volume-control.svg
scalable/volume.svg: source/multimedia-volume-control.svg
scalable/xfce4-mixer.svg: source/multimedia-volume-control.svg
scalable/mixer.svg: source/multimedia-volume-control.svg
scalable/pulseaudio.svg: source/multimedia-volume-control.svg
scalable/padevchooser.svg: source/multimedia-volume-control.svg
scalable/gnome-games.svg: source/naipes.svg
scalable/sol.svg: source/naipes.svg
scalable/network-cellular-3g.svg: source/network-3g.svg
scalable/network-cellular-3g-symbolic.svg: source/network-3g.svg
scalable/network-cellular-4g.svg: source/network-4g.svg
scalable/network-cellular-4g-symbolic.svg: source/network-4g.svg
scalable/network-cellular-connected-symbolic.svg: source/network-cellular-connected.svg
scalable/network-cellular-edge.svg: source/network-edge.svg
scalable/network-cellular-edge-symbolic.svg: source/network-edge.svg
scalable/network-cellular-gprs.svg: source/network-gprs.svg
scalable/network-cellular-gprs-symbolic.svg: source/network-gprs.svg
scalable/network-cellular-hspa.svg: source/network-hspa.svg
scalable/network-cellular-hspa-symbolic.svg: source/network-hspa.svg
scalable/internet.svg: source/network_r4.svg
scalable/emblem-web.svg: source/network_r4.svg
scalable/gnome-fs-server.svg: source/network-server.svg
scalable/gnome-mime-x-directory-nfs-server.svg: source/network-server.svg
scalable/gnome-mime-x-directory-smb-server.svg: source/network-server.svg
scalable/redhat-network-server.svg: source/network-server.svg
scalable/server.svg: source/network-server.svg
scalable/gnome-fs-network.svg: source/network-workgroup.svg
scalable/gnome-mime-x-directory-smb-workgroup.svg: source/network-workgroup.svg
scalable/gtk-network.svg: source/network-workgroup.svg
scalable/network_local.svg: source/network-workgroup.svg
scalable/fly-red.svg: source/neurokernel.github.io-fly.svg
scalable/internet-news-reader.svg: source/news.svg
scalable/mail-folder-outbox.svg: source/outbox.svg
scalable/squeeze.svg: source/package-maker.svg
scalable/xarchiver.svg: source/package-maker.svg
scalable/compressor.svg: source/package-maker.svg
scalable/ark.svg: source/package-maker.svg
scalable/gnome-mplayer.svg: source/palomitas.svg
scalable/movie-player.svg: source/palomitas.svg
scalable/totem.svg: source/palomitas.svg
scalable/application-x-perl.svg: source/perlscript.svg
scalable/text-x-perl.svg: source/perlscript.svg
scalable/application-x-person.svg: source/person.svg
scalable/avatar-default.svg: source/person.svg
scalable/avatar-default-symbolic.svg: source/person.svg
scalable/stock_person.svg: source/person.svg
scalable/user.svg: source/person.svg
scalable/stock_cell-phone.svg: source/phone.svg
scalable/window-stick.svg: source/pin-up.svg
scalable/xkill.svg: source/pirate.svg
scalable/sumar.svg: source/plus.svg
scalable/list-add.svg: source/plus.svg
scalable/add.svg: source/plus.svg
scalable/gtk-add.svg: source/plus.svg
scalable/xfsm-shutdown.svg: source/poweroff-cpu.svg
scalable/access.svg: source/preferences-desktop-accessibility.svg
scalable/gnome-settings-accessibility-technologies.svg: source/preferences-desktop-accessibility.svg
scalable/display-capplet.svg: source/preferences-desktop-display.svg
scalable/gnome-display-properties.svg: source/preferences-desktop-display.svg
scalable/gsd-xrandr.svg: source/preferences-desktop-display.svg
scalable/gnome-settings-keybindings.svg: source/preferences-desktop-keyboard-shortcuts.svg
scalable/key_bindings.svg: source/preferences-desktop-keyboard-shortcuts.svg
scalable/config-language.svg: source/preferences-desktop-locale.svg
scalable/locale.svg: source/preferences-desktop-locale.svg
scalable/input_devices_settings.svg: source/preferences-desktop-peripherals.svg
scalable/gnome-remote-desktop.svg: source/preferences-desktop-remote-desktop.svg
scalable/krfb.svg: source/preferences-desktop-remote-desktop.svg
scalable/package_settings.svg: source/preferences-system.svg
scalable/redhat-system_settings.svg: source/preferences-system.svg
scalable/xfce-system-settings.svg: source/preferences-system.svg
scalable/gnome-session.svg: source/preferences-system-session.svg
scalable/gnome-window-manager.svg: source/preferences-system-windows.svg
scalable/kcmkwm.svg: source/preferences-system-windows.svg
scalable/kwin.svg: source/preferences-system-windows.svg
scalable/printer-error-symbolic.svg: source/printer-error.svg
scalable/gnome-dev-printer.svg: source/printer.svg
scalable/kjobviewer.svg: source/printer.svg
scalable/printer1.svg: source/printer.svg
scalable/printer-remote.svg: source/printer.svg
scalable/printmgr.svg: source/printer.svg
scalable/print.svg: source/printer.svg
scalable/stock_printers.svg: source/printer.svg
scalable/xfce-printer.svg: source/printer.svg
scalable/yast_printer.svg: source/printer.svg
scalable/printer-printing-symbolic.svg: source/printer-printing.svg
scalable/printer-warning-symbolic.svg: source/printer-warning.svg
scalable/lxtask.svg: source/procman.svg
scalable/xosview.svg: source/procman.svg
scalable/help_book.svg: source/question-book.svg
scalable/go-jump.svg: source/retrosmart-app_beacon.svg
scalable/gtk-jump-to-ltr.svg: source/retrosmart-app_beacon.svg
scalable/gtk-jump-to-rtl.svg: source/retrosmart-app_beacon.svg
scalable/application.svg: source/retrosmart-application.svg
scalable/rubyripper.svg: source/retrosmart-app-rubyripper.svg
scalable/emblem-system.svg: source/retrosmart-atom-red.svg
scalable/atom.svg: source/retrosmart-atom-red.svg
scalable/katomic.svg: source/retrosmart-atom-red.svg
scalable/application-octet-stream.svg: source/retrosmart-binary-stream.svg
scalable/application-x-executable-binary.svg: source/retrosmart-binary-stream.svg
scalable/application-x-macbinary.svg: source/retrosmart-binary-stream.svg
scalable/media-optical-bluray.svg: source/retrosmart-bluray.svg
scalable/code-variable.svg: source/retrosmart-box-white.svg
scalable/media-optical-audio.svg: source/retrosmart-cd-audio.svg
scalable/cd-audio.svg: source/retrosmart-cd-audio.svg
scalable/gnome-cd.svg: source/retrosmart-cd-audio.svg
scalable/gnome-dev-cdrom-audio.svg: source/retrosmart-cd-audio.svg
scalable/gnome-cd-audio.svg: source/retrosmart-cd-audio.svg
scalable/stock_xfburn-audio-cd.svg: source/retrosmart-cd-audio.svg
scalable/stock_xfburn-blank-cdrw.svg: source/retrosmart-cd-blank.svg
scalable/media-optical-data.svg: source/retrosmart-cd-data.svg
scalable/cd-player.svg: source/retrosmart-cd-player.svg
scalable/gnome-cd-player.svg: source/retrosmart-cd-player.svg
scalable/ario.svg: source/retrosmart-cd-player.svg
scalable/sonata.svg: source/retrosmart-cd-player.svg
scalable/gnome-cdplayer.svg: source/retrosmart-cd-player.svg
scalable/gnome-cdplayer-icon.svg: source/retrosmart-cd-player.svg
scalable/ario-play.svg: source/retrosmart-cd-player-play.svg
scalable/utilities-terminal.svg: source/retrosmart-crt-terminal.svg
scalable/gnome-terminal.svg: source/retrosmart-crt-terminal.svg
scalable/konsole.svg: source/retrosmart-crt-terminal.svg
scalable/lxterminal.svg: source/retrosmart-crt-terminal.svg
scalable/monitor.svg: source/retrosmart-crt-terminal.svg
scalable/openterm.svg: source/retrosmart-crt-terminal.svg
scalable/roxterm.svg: source/retrosmart-crt-terminal.svg
scalable/sakura.svg: source/retrosmart-crt-terminal.svg
scalable/terminal.svg: source/retrosmart-crt-terminal.svg
scalable/Terminal.svg: source/retrosmart-crt-terminal.svg
scalable/xfce-terminal.svg: source/retrosmart-crt-terminal.svg
scalable/x-terminal-emulator.svg: source/retrosmart-crt-terminal.svg
scalable/gdu-check-disk.svg: source/retrosmart-device-harddisk-check.svg
scalable/bleachbit.svg: source/retrosmart-device-harddisk-clean.svg
scalable/gdu-info.sg.svg: source/retrosmart-device-harddisk-info.svg
scalable/disk-new.svg: source/retrosmart-device-harddisk-new.svg
scalable/gdu-mount.svg: source/retrosmart-device-harddisk-play.svg
scalable/gdu-unmount.svg: source/retrosmart-device-harddisk-stop.svg
scalable/gdu-warning.svg: source/retrosmart-device-harddisk-warning.svg
scalable/xfce4-dict.svg: source/retrosmart-dictionary.svg
scalable/accessories-dictionary.svg: source/retrosmart-dictionary.svg
scalable/fantasdic.svg: source/retrosmart-dictionary.svg
scalable/insert-footnote.svg: source/retrosmart-document-footnote-new.svg
scalable/document-save-all.svg: source/retrosmart-document-save-all.svg
scalable/document-save-as-template.svg: source/retrosmart-document-save-as-template.svg
scalable/shellscript.svg: source/retrosmart-document-shellscript.svg
scalable/application-x-shellscript.svg: source/retrosmart-document-shellscript.svg
scalable/text-x-csh.svg: source/retrosmart-document-shellscript.svg
scalable/file-text.svg: source/retrosmart-document-text.svg
scalable/kt-add-filters.svg: source/retrosmart-funnel-add.svg
scalable/view-filter.svg: source/retrosmart-funnel.svg
scalable/kt-remove-filters.svg: source/retrosmart-funnel-remove.svg
scalable/image-missing.svg: source/retrosmart-image-broken.svg
scalable/brokenimage.svg: source/retrosmart-image-broken.svg
scalable/gtk-missing-image.svg: source/retrosmart-image-broken.svg
scalable/missing-image.svg: source/retrosmart-image-broken.svg
scalable/image-gif.svg: source/retrosmart-image-gif.svg
scalable/gnome-mime-image-gif.svg: source/retrosmart-image-gif.svg
scalable/application-x-krita.svg: source/retrosmart-application-image-krita.svg
scalable/image-jpeg.svg: source/retrosmart-image-jpeg.svg
scalable/image-jxl.svg: source/retrosmart-image-jxl.svg
scalable/gnome-mime-image-jpeg.svg: source/retrosmart-image-jpeg.svg
scalable/image-png.svg: source/retrosmart-image-png.svg
scalable/gnome-mime-image-png.svg: source/retrosmart-image-png.svg
scalable/image-svg+xml-compressed.svg: source/retrosmart-image-svg+xml-compressed.svg
scalable/image-svg+xml.svg: source/retrosmart-image-svg+xml.svg
scalable/image-tiff.svg: source/retrosmart-image-tiff.svg
scalable/image-vnd.dgn.svg: source/retrosmart-image-vnd.dgn.svg
scalable/image-vnd.djvu.svg: source/retrosmart-image-vnd.djvu.svg
scalable/image-vnd.dwg.svg: source/retrosmart-image-vnd.dwg.svg
scalable/image-x-adobe-dng.svg: source/retrosmart-image-x-adobe-dng.svg
scalable/image-xcf.svg: source/retrosmart-image-xcf.svg
scalable/image-x-xcf.svg: source/retrosmart-image-xcf.svg
scalable/image-x-icon.svg: source/retrosmart-image-x-ico.svg
scalable/image-x-psd.svg: source/retrosmart-image-x-psd.svg
scalable/image-x-tga.svg: source/retrosmart-image-x-tga.svg
scalable/image-x-vnd.trolltech.qpicture.svg: source/retrosmart-image-x-vnd.trolltech.qpicture.svg
scalable/image-xpixmap.svg: source/retrosmart-image-x-xpixmap.svg
scalable/info-contents.svg: source/retrosmart-info-document.svg
scalable/help-contents.svg: source/retrosmart-info-document.svg
scalable/text-x-texinfo.svg: source/retrosmart-info-document.svg
scalable/application-x-gnome-app-info.svg: source/retrosmart-info-document.svg
scalable/kgpg.svg: source/retrosmart-lock-wide-close.svg
scalable/uget-icon.svg: source/retrosmart-magnet.svg
scalable/kt-magnet.svg: source/retrosmart-magnet.svg
scalable/application-menu.svg: source/retrosmart-menu.svg
scalable/show-menu.svg: source/retrosmart-menu.svg
scalable/menu_new_sep.svg: source/retrosmart-menu-separator.svg
scalable/knemo-wireless-error.svg: source/retrosmart-misc-antenna-error.svg
scalable/knemo-wireless-idle.svg: source/retrosmart-misc-antenna-idle.svg
scalable/knemo-wireless-offline.svg: source/retrosmart-misc-antenna-offline.svg
scalable/network-wireless-offline.svg: source/retrosmart-misc-antenna-offline.svg
scalable/network-wireless-offline-symbolic.svg: source/retrosmart-misc-antenna-offline.svg
scalable/knemo-wireless-receive.svg: source/retrosmart-misc-antenna-receive.svg
scalable/network-wireless.svg: source/retrosmart-misc-antenna-receive.svg
scalable/gnome-dev-wavelan.svg: source/retrosmart-misc-antenna-receive.svg
scalable/nm-device-wwan.svg: source/retrosmart-misc-antenna-receive.svg
scalable/knemo-wireless-transmit.svg: source/retrosmart-misc-antenna-transmit.svg
scalable/knemo-wireless-transmit-receive.svg: source/retrosmart-misc-antenna-transmit-receive.svg
scalable/multimedia-player.svg: source/retrosmart-multimedia-player.svg
scalable/multimedia-player-ipod-mini-blue.svg: source/retrosmart-multimedia-player.svg
scalable/gnome-dev-ipod.svg: source/retrosmart-multimedia-player.svg
scalable/ipod_mount.svg: source/retrosmart-multimedia-player.svg
scalable/gmpc.svg: source/retrosmart-music-daemon.svg
scalable/cantata.svg: source/retrosmart-music-daemon.svg
scalable/xfmpc.svg: source/retrosmart-music-daemon.svg
scalable/network-error.svg: source/retrosmart-network-error.svg
scalable/gnome-netstatus-error.svg: source/retrosmart-network-error.svg
scalable/network-error-symbolic.svg: source/retrosmart-network-error.svg
scalable/gnome-network-properites.svg: source/retrosmart-network-info.svg
scalable/network-offline.svg: source/retrosmart-network-offline.svg
scalable/knemo-network-offline.svg: source/retrosmart-network-offline.svg
scalable/connect_no.svg: source/retrosmart-network-offline.svg
scalable/gnome-netstatus-disconn.svg: source/retrosmart-network-offline.svg
scalable/network-offline-symbolic.svg: source/retrosmart-network-offline.svg
scalable/preferences-system-network-proxy.svg: source/retrosmart-network-proxy.svg
scalable/proxy-config.svg: source/retrosmart-network-proxy.svg
scalable/proxy.svg: source/retrosmart-network-proxy.svg
scalable/stock_proxy.svg: source/retrosmart-network-proxy.svg
scalable/network-receive.svg: source/retrosmart-network-receive.svg
scalable/knemo-network-receive.svg: source/retrosmart-network-receive.svg
scalable/gnome-netstatus-rx.svg: source/retrosmart-network-receive.svg
scalable/network-receive-symbolic.svg: source/retrosmart-network-receive.svg
scalable/preferences-system-network-sharing.svg: source/retrosmart-network-share.svg
scalable/network-transmit.svg: source/retrosmart-network-transmit.svg
scalable/knemo-network-transmit.svg: source/retrosmart-network-transmit.svg
scalable/gnome-netstatus-tx.svg: source/retrosmart-network-transmit.svg
scalable/network-transmit-symbolic.svg: source/retrosmart-network-transmit.svg
scalable/network-transmit-receive.svg: source/retrosmart-network-transmit-receive.svg
scalable/knemo-network-transmit-receive.svg: source/retrosmart-network-transmit-receive.svg
scalable/connect_creating.svg: source/retrosmart-network-transmit-receive.svg
scalable/gnome-netstatus-txrx.svg: source/retrosmart-network-transmit-receive.svg
scalable/network-transmit-receive-symbolic.svg: source/retrosmart-network-transmit-receive.svg
scalable/filter-note-all.svg: source/retrosmart-note-all.svg
scalable/notebook-new.svg: source/retrosmart-notebook-new.svg
scalable/sage-notebook.svg: source/retrosmart-notebook-sage.svg
scalable/QOwnNotes.svg: source/retrosmart-note-cloud.svg
scalable/note.svg: source/retrosmart-note.svg
scalable/gnome-sticky-notes-applet.svg: source/retrosmart-note.svg
scalable/xfce4-notes-plugin.svg: source/retrosmart-note.svg
scalable/knotes.svg: source/retrosmart-note.svg
scalable/gnote.svg: source/retrosmart-note-pin.svg
scalable/xpad.svg: source/retrosmart-note-pin.svg
scalable/libreoffice-math.svg: source/retrosmart-office-document-math.svg
scalable/onboard.svg: source/retrosmart-on-screen-keyboard.svg
scalable/playlist-browser.svg: source/retrosmart-playlist-browser.svg
scalable/playlist-editor.svg: source/retrosmart-playlist-editor.svg
scalable/playlist-search-browser.svg: source/retrosmart-playlist-search-browser.svg
scalable/revert-to-saved.svg: source/retrosmart-revert-to-saved.svg
scalable/stock-revert-to-saved.svg: source/retrosmart-revert-to-saved.svg
scalable/network-connect.svg: source/retrosmart-rj45-connected.svg
scalable/knemo-network-error.svg: source/retrosmart-rj45-error.svg
scalable/network-wired.svg: source/retrosmart-rj45.svg
scalable/gnome-dev-ethernet.svg: source/retrosmart-rj45.svg
scalable/network-wired-offline.svg: source/retrosmart-rj45-offline.svg
scalable/network-disconnect.svg: source/retrosmart-rj45-offline.svg
scalable/network-wired-disconnected.svg: source/retrosmart-rj45-offline.svg
scalable/network-wired-disconnected-symbolic.svg: source/retrosmart-rj45-offline.svg
scalable/network-wired-offline-symbolic.svg: source/retrosmart-rj45-offline.svg
scalable/gtk-select-color.svg: source/retrosmart-select-color.svg
scalable/kcolorchooser.svg: source/retrosmart-select-color.svg
scalable/gcolor2.svg: source/retrosmart-select-color.svg
scalable/socket.svg: source/retrosmart-socket-white.svg
scalable/inode-socket.svg: source/retrosmart-socket-white.svg
scalable/xfpm-ac-adapter.svg: source/retrosmart-socket-white.svg
scalable/text-x-haskell.svg: source/retrosmart-text-x-haskell.svg
scalable/totem-tv.svg: source/retrosmart-tv.svg
scalable/gnome-dev-tv.svg: source/retrosmart-tv.svg
scalable/gnome-panel-window-menu.svg: source/retrosmart-window-menu.svg
scalable/perlpanel-applet-windowmenu.svg: source/retrosmart-window-menu.svg
scalable/exaile.svg: source/rhythmbox.svg
scalable/gnome-dev-scanner.svg: source/scanner.svg
scalable/sane.svg: source/scanner.svg
scalable/xsane.svg: source/scanner.svg
scalable/edit-cut.svg: source/scissors.svg
scalable/cut.svg: source/scissors.svg
scalable/editcut.svg: source/scissors.svg
scalable/gtk-cut.svg: source/scissors.svg
scalable/stock_cut.svg: source/scissors.svg
scalable/text-x-script.svg: source/script.svg
scalable/text-x-sh.svg: source/script.svg
scalable/application-x-python-bytecode.svg: source/script.svg
scalable/stock_script.svg: source/script.svg
scalable/text-x-zsh.svg: source/script.svg
scalable/security-low.svg: source/security-critical.svg
scalable/stock_lock-broken.svg: source/security-critical.svg
scalable/stock_lock-open.svg: source/security-critical.svg
scalable/security-low-symbolic.svg: source/security-critical.svg
scalable/security-medium.svg: source/security-ok.svg
scalable/stock_lock.svg: source/security-ok.svg
scalable/security-medium-symbolic.svg: source/security-ok.svg
scalable/security-high.svg: source/security-up.svg
scalable/stock_lock-ok.svg: source/security-up.svg
scalable/security-high-symbolic.svg: source/security-up.svg
scalable/xfce-sensors.svg: source/sensors.svg
scalable/ajustes.svg: source/settings.svg
scalable/systemsettings.svg: source/settings.svg
scalable/software-update-available-symbolic.svg: source/software-update-available.svg
scalable/software-update-urgent-symbolic.svg: source/software-update-urgent.svg
scalable/soundconverter.svg: source/sound-converter.svg
scalable/xfce4-mixer-no-muted.svg: source/speaker-no-muted.svg
scalable/estrella.svg: source/star.svg
scalable/emblem-special.svg: source/star.svg
scalable/gnome-sudoku.svg: source/sudoku.svg
scalable/emblem-symbolic-link.svg: source/symlink.svg
scalable/rox-symlink.svg: source/symlink.svg
scalable/applications-system.svg: source/system_kernel.svg
scalable/gnome-system.svg: source/system_kernel.svg
scalable/package_system.svg: source/system_kernel.svg
scalable/redhat-system_tools.svg: source/system_kernel.svg
scalable/xfce-system.svg: source/system_kernel.svg
scalable/system.svg: source/system_kernel.svg
scalable/lock.svg: source/system-lock-screen.svg
scalable/xfce-system-lock.svg: source/system-lock-screen.svg
scalable/gnome-logout.svg: source/system-log-out.svg
scalable/gnome-session-logout.svg: source/system-log-out.svg
scalable/reboot-cpu.svg: source/system-reboot.svg
scalable/kfind.svg: source/system-search.svg
scalable/system-search-32.svg: source/system-search.svg
scalable/gnome-shutdown.svg: source/system-shutdown.svg
scalable/system-installer.svg: source/system-software-install.svg
scalable/gnome-codec-install.svg: source/system-software-install.svg
scalable/update-manager.svg: source/system-software-update.svg
scalable/zen-icon.svg: source/system-software-update.svg
scalable/icon-update.svg: source/system-software-update.svg
scalable/gnome-inhibit-applet.svg: source/system-suspend.svg
scalable/xfpm-suspend.svg: source/system-suspend.svg
scalable/config-users.svg: source/system-users.svg
scalable/kuser.svg: source/system-users.svg
scalable/redhat-config-users.svg: source/system-users.svg
scalable/system-config-users.svg: source/system-users.svg
scalable/easytag.svg: source/tag-editor.svg
scalable/tagtool.svg: source/tag-editor.svg
scalable/tags.svg: source/tag.svg
scalable/media-tag.svg: source/tag.svg
scalable/tag-browser.svg: source/tag.svg
scalable/diana.svg: source/target.svg
scalable/window-center.svg: source/target.svg
scalable/task-due-symbolic.svg: source/task-due.svg
scalable/task-past-due-symbolic.svg: source/task-past-due.svg
scalable/telegram_logo.svg: source/telegram.svg
scalable/telegram-messenger.svg: source/telegram.svg
scalable/video-television.svg: source/television.svg
scalable/geany.svg: source/tetera_amarilla.svg
scalable/gedit-icon.svg: source/text-editor.svg
scalable/accessories-text-editor.svg: source/text-editor.svg
scalable/kedit.svg: source/text-editor.svg
scalable/xfce-edit.svg: source/text-editor.svg
scalable/leafpad.svg: source/text-editor.svg
scalable/gpe-edit.svg: source/text-editor.svg
scalable/mousepad.svg: source/text-editor.svg
scalable/application-vnd.oasis.opendocument.text-web.svg: source/text-html.svg
scalable/application-x-php.svg: source/text-html.svg
scalable/html.svg: source/text-html.svg
scalable/mime-text-html.svg: source/text-html.svg
scalable/text-vnd.wap.wml.svg: source/text-html.svg
scalable/www.svg: source/text-html.svg
scalable/gnome-mime-text-html.svg: source/text-html.svg
scalable/consoleonly.svg: source/text_mode.svg
scalable/modo_texto.svg: source/text_mode.svg
scalable/text-x-c-header.svg: source/text-x-chdr.svg
scalable/text-x-c++src.svg: source/text-x-c++.svg
scalable/text-x-diff.svg: source/haikuos-file_patch.svg
scalable/text-x-patch.svg: source/haikuos-file_patch.svg
scalable/ascii.svg: source/text-x-generic.svg
scalable/empty.svg: source/text-x-generic.svg
scalable/mime_ascii.svg: source/text-x-generic.svg
scalable/misc.svg: source/text-x-generic.svg
scalable/package_editors.svg: source/text-x-generic.svg
scalable/texto.svg: source/text-x-generic.svg
scalable/text.svg: source/text-x-generic.svg
scalable/txt2.svg: source/text-x-generic.svg
scalable/txt.svg: source/text-x-generic.svg
scalable/unknown.svg: source/text-x-generic.svg
scalable/template_source.svg: source/text-x-generic-template.svg
scalable/gnome-mime-text-x-install.svg: source/text-x-install.svg
scalable/application-x-lyx.svg: source/text-x-lyx.svg
scalable/application-x-ruby.svg: source/text-x-ruby.svg
scalable/gnome-mime-text-x-vcalendar.svg: source/text-x-vcalendar.svg
scalable/preferences-other.svg: source/toolbox.svg
scalable/gtk-spell-check.svg: source/tools-check-spelling.svg
scalable/stock_spellcheck.svg: source/tools-check-spelling.svg
scalable/gtk-preferences.svg: source/tools.svg
scalable/herramientas.svg: source/tools.svg
scalable/icon-system-tools.svg: source/tools.svg
scalable/preferences.svg: source/tools.svg
scalable/user-away-symbolic.svg: source/user-away.svg
scalable/user-busy-symbolic.svg: source/user-busy.svg
scalable/folder_home.svg: source/user-home.svg
scalable/gnome-fs-home.svg: source/user-home.svg
scalable/user-idle-symbolic.svg: source/user-idle.svg
scalable/user-invisible-symbolic.svg: source/user-invisible.svg
scalable/user-offline-symbolic.svg: source/user-offline.svg
scalable/gaim_offline.svg: source/user-offline.svg
scalable/user-online-symbolic.svg: source/user-online.svg
scalable/gaim_online.svg: source/user-online.svg
scalable/user-available.svg: source/user-online.svg
scalable/user-available-symbolic.svg: source/user-online.svg
scalable/user-status-pending-symbolic.svg: source/user-status-pending.svg
scalable/gnome-fs-trash-full.svg: source/user-trash-full.svg
scalable/gnome-stock-trash-full.svg: source/user-trash-full.svg
scalable/stock_trash_full.svg: source/user-trash-full.svg
scalable/trashcan_full.svg: source/user-trash-full.svg
scalable/xfce-trash_full.svg: source/user-trash-full.svg
scalable/user-trash-full-symbolic.svg: source/user-trash-full.svg
scalable/edittrash.svg: source/user-trash.svg
scalable/emptytrash.svg: source/user-trash.svg
scalable/gnome-fs-trash-empty.svg: source/user-trash.svg
scalable/gnome-stock-trash.svg: source/user-trash.svg
scalable/trashcan_empty.svg: source/user-trash.svg
scalable/trash.svg: source/user-trash.svg
scalable/xfce-trash_empty.svg: source/user-trash.svg
scalable/gnome-monitor.svg: source/utilities-system-monitor.svg
scalable/gnome-system-monitor.svg: source/utilities-system-monitor.svg
scalable/ksysguard.svg: source/utilities-system-monitor.svg
scalable/xfce4-taskmanager.svg: source/utilities-system-monitor.svg
scalable/display.svg: source/video-display.svg
scalable/xfce4-display.svg: source/video-display.svg
scalable/gnome-mime-video.svg: source/video.svg
scalable/gnome-mime-video-mpeg.svg: source/video-mpeg.svg
scalable/gnome-mime-video-quicktime.svg: source/video-quicktime.svg
scalable/application-vnd.rn-realmedia-secure.svg: source/video-x-generic.svg
scalable/application-vnd.rn-realmedia-vbr.svg: source/video-x-generic.svg
scalable/gnome-mime-video-x-ms-asf.svg: source/video-x-ms-asf.svg
scalable/video-vnd.avi.svg: source/video-x-msvideo.svg
scalable/gnome-mime-video-x-msvideo.svg: source/video-x-msvideo.svg
scalable/gnome-mime-video-x-ms-wmv.svg: source/video-x-ms-wmv.svg
scalable/video-x-wmv.svg: source/video-x-ms-wmv.svg
scalable/video-ogg.svg: source/video-x-ogm+ogg.svg
scalable/rox-show-details.svg: source/view-details.svg
scalable/gtk-fullscreen.svg: source/view-fullscreen.svg
scalable/stock_fullscreen.svg: source/view-fullscreen.svg
scalable/window_fullscreen.svg: source/view-fullscreen.svg
scalable/gtk-leave-fullscreen.svg: source/view-restore.svg
scalable/stock_leave-fullscreen.svg: source/view-restore.svg
scalable/window_nofullscreen.svg: source/view-restore.svg
scalable/gtk-sort-ascending.svg: source/view-sort-ascending.svg
scalable/gtk-sort-descending.svg: source/view-sort-descending.svg
scalable/gvim.svg: source/vim.svg
scalable/stock_weather-sunny.svg: source/weather-clear.svg
scalable/sunny.svg: source/weather-clear.svg
scalable/weather-clear-symbolic.svg: source/weather-clear.svg
scalable/stock_weather-night-clear.svg: source/weather-clear-night.svg
scalable/weather-clear-night-symbolic.svg: source/weather-clear-night.svg
scalable/stock_weather-few-clouds.svg: source/weather-few-clouds.svg
scalable/weather-few-clouds-symbolic.svg: source/weather-few-clouds.svg
scalable/stock_weather-night-few-clouds.svg: source/weather-few-clouds-night.svg
scalable/weather-few-clouds-night-symbolic.svg: source/weather-few-clouds-night.svg
scalable/stock_weather-fog.svg: source/weather-fog.svg
scalable/weather-fog-symbolic.svg: source/weather-fog.svg
scalable/stock_weather-cloudy.svg: source/weather-overcast.svg
scalable/weather-overcast-symbolic.svg: source/weather-overcast.svg
scalable/weather-severe-alert-symbolic.svg: source/weather-severe-alert.svg
scalable/stock_weather-showers.svg: source/weather-showers.svg
scalable/weather-showers-symbolic.svg: source/weather-showers.svg
scalable/weather-showers-scattered-symbolic.svg: source/weather-showers-scattered.svg
scalable/stock_weather-snow.svg: source/weather-snow.svg
scalable/weather-snow-symbolic.svg: source/weather-snow.svg
scalable/stock_weather-storm.svg: source/weather-storm.svg
scalable/weather-storm-symbolic.svg: source/weather-storm.svg
scalable/web-browser.svg: source/webpositive_r2.svg
scalable/chromium-browser.svg: source/webpositive_r2.svg
scalable/chromium.svg: source/webpositive_r2.svg
scalable/qupzilla.svg: source/webpositive_r2.svg
scalable/epiphany.svg: source/webpositive_r2.svg
scalable/internet-web-browser.svg: source/webpositive_r2.svg
scalable/webbrowser.svg: source/webpositive_r2.svg
scalable/x-www-browser.svg: source/webpositive_r2.svg
scalable/browser.svg: source/webpositive_r2.svg
scalable/redhat-web-browser.svg: source/webpositive_r2.svg
scalable/gnome-web-browser.svg: source/webpositive_r2.svg
scalable/gtk-close.svg: source/window-close.svg
scalable/stock_close.svg: source/window-close.svg
scalable/wmtweaks.svg: source/window-magic.svg
scalable/winwrangler.svg: source/window-mosaic.svg
scalable/stock_new-window.svg: source/window-new.svg
scalable/window_new.svg: source/window-new.svg
scalable/page.svg: source/window-page.svg
scalable/ccsm.svg: source/window-preferences.svg
scalable/welcome_wizard.svg: source/wizard.svg
scalable/gnome-panel-workspace-switcher.svg: source/workspaces.svg
scalable/xfce4-workspaces.svg: source/workspaces.svg
scalable/gnome-lockscreen.svg: source/xlock.svg
scalable/panel-lockscreen.svg: source/xlock.svg
scalable/contents2.svg: source/x-office-address-book.svg
scalable/stock_addressbook.svg: source/x-office-address-book.svg
scalable/application-vnd.ms-word.document.macroEnabled.12.svg: source/x-office-document.svg
scalable/application-vnd.openxmlformats-officedocument.wordprocessingml.document.svg: source/x-office-document.svg
scalable/application-wordperfect.svg: source/x-office-document.svg
scalable/application-x-applix-word.svg: source/x-office-document.svg
scalable/application-x-scribus.svg: source/x-office-document.svg
scalable/document.svg: source/x-office-document.svg
scalable/package_wordprocessing.svg: source/x-office-document.svg
scalable/wordprocessing.svg: source/x-office-document.svg
scalable/application-magicpoint.svg: source/x-office-presentation.svg
scalable/application-vnd.ms-powerpoint.presentation.macroEnabled.12.svg: source/x-office-presentation.svg
scalable/application-vnd.openxmlformats-officedocument.presentationml.presentation.svg: source/x-office-presentation.svg
scalable/application-vnd.stardivision.impress.svg: source/x-office-presentation.svg
scalable/kpresenter_kpr.svg: source/x-office-presentation.svg
scalable/application-vnd.lotus-1-2-3.svg: source/x-office-spreadsheet.svg
scalable/application-vnd.ms-excel.sheet.macroEnabled.12.svg: source/x-office-spreadsheet.svg
scalable/application-vnd.openxmlformats-officedocument.spreadsheetml.sheet.svg: source/x-office-spreadsheet.svg
scalable/application-vnd.stardivision.calc.svg: source/x-office-spreadsheet.svg
scalable/application-x-applix-spreadsheet.svg: source/x-office-spreadsheet.svg
scalable/spreadsheet.svg: source/x-office-spreadsheet.svg
scalable/gnome-mime-application-x-xoj.svg: source/xoj.svg
scalable/gtk-zoom-fit.svg: source/zoom-fit-best.svg
scalable/stock_zoom-page.svg: source/zoom-fit-best.svg
scalable/viewmagfit.svg: source/zoom-fit-best.svg
scalable/zoom-best-fit.svg: source/zoom-fit-best.svg
scalable/gtk-zoom-in.svg: source/zoom-in.svg
scalable/stock_zoom-in.svg: source/zoom-in.svg
scalable/viewmag+.svg: source/zoom-in.svg
scalable/gtk-zoom-100.svg: source/zoom-original.svg
scalable/stock_zoom-1.svg: source/zoom-original.svg
scalable/viewmag1.svg: source/zoom-original.svg
scalable/zoom-1.svg: source/zoom-original.svg
scalable/gtk-zoom-out.svg: source/zoom-out.svg
scalable/stock_zoom-out.svg: source/zoom-out.svg
scalable/viewmag-.svg: source/zoom-out.svg
scalable/view-refresh.svg: source/zumi.xoom.it-3rd_party_apps-wayback.svg
scalable/gtk-refresh.svg: source/zumi.xoom.it-3rd_party_apps-wayback.svg
scalable/reload_all_tabs.svg: source/zumi.xoom.it-3rd_party_apps-wayback.svg
scalable/reload_page.svg: source/zumi.xoom.it-3rd_party_apps-wayback.svg
scalable/reload.svg: source/zumi.xoom.it-3rd_party_apps-wayback.svg
scalable/stock_refresh.svg: source/zumi.xoom.it-3rd_party_apps-wayback.svg
scalable/navigation_reload.svg: source/zumi.xoom.it-3rd_party_apps-wayback.svg
scalable/refresh.svg: source/zumi.xoom.it-3rd_party_apps-wayback.svg
scalable/colorpicker.svg: source/zumi.xoom.it-miscellaneous-color_picker.svg
scalable/donate.svg: source/zumi.xoom.it-miscellaneous-piggy_bank.svg
scalable/applications-science.svg: source/zumi.xoom.it-miscellaneous-science.svg
scalable/dialog.svg: source/zumi.xoom.it-system-chat_r2_altcol.svg
scalable/audio-headphones.svg: source/zumi.xoom.it-system-earphones.svg
scalable/help.svg: source/zumi.xoom.it-system-help.svg
scalable/system-help.svg: source/zumi.xoom.it-system-help.svg
scalable/gnome-help.svg: source/zumi.xoom.it-system-help.svg
scalable/gtk-help.svg: source/zumi.xoom.it-system-help.svg
scalable/stock_help.svg: source/zumi.xoom.it-system-help.svg
scalable/filter-note-unfiled.svg: source/zumi.xoom.it-system-note_r2.svg
